'use client';
import { useEffect,useMemo,useState } from 'react';
import AppShell from '@/components/AppShell';import AuthGate from '@/components/AuthGate';import GlassCard from '@/components/GlassCard';import RichTextEditor from '@/components/RichTextEditor';import RichHtml from '@/components/RichHtml';import { api } from '@/lib/api';import { rubricFor,rubricScore100,type TaskRubric } from '@/lib/taskRubrics';
import { Save,ExternalLink,MessageSquareText,Download,Upload,FileSpreadsheet,CheckCircle2,AlertTriangle } from 'lucide-react';

type Activity={activity_id:string;title:string;type:string;max_score:number;week_id:string};
type Roster={user:{user_id:string;nim:string;name:string;class_name?:string};grade?:{score:number;max_score:number;feedback_html:string;published:boolean}|null;submission?:{submission_id:string;link_url:string;file_url:string;file_name?:string;content_html:string;submitted_at?:string}|null;post_count?:number;discussion_excerpt?:string;has_comment?:boolean};
type EvalResponse={rubric:{rubric_id:string;activity_id:string;name:string;criteria:Array<{id:string;name:string;weight:number;levels:Array<{score:number;description:string}>}>;note?:string;source_weight_total?:number}|null;evaluation:{scores:Record<string,number>;total_score:number}|null};
type ImportRow={activity_id:string;user_id:string;submission_id:string;score:string;comment:string;name:string;nim:string};
type ImportReport={processed:number;grade_records:number;comments:number;group_rows:number;errors:string[]};

function strip(v:string){return String(v||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
export default function Gradebook(){
 const[activities,setActivities]=useState<Activity[]>([]),[activity,setActivity]=useState(''),[rows,setRows]=useState<Roster[]>([]),[selected,setSelected]=useState<Roster|null>(null),[score,setScore]=useState(0),[feedback,setFeedback]=useState(''),[comment,setComment]=useState(''),[published,setPublished]=useState(true),[rubricScores,setRubricScores]=useState<Record<string,number>>({}),[msg,setMsg]=useState('');
 const[importRows,setImportRows]=useState<ImportRow[]>([]),[importName,setImportName]=useState(''),[busy,setBusy]=useState(false);
 const current=activities.find(x=>x.activity_id===activity),localRubric:TaskRubric|undefined=rubricFor(activity);
 const loadActivities=()=>api<Activity[]>('adminGradebookActivities').then(a=>{setActivities(a);setActivity(v=>v||a[0]?.activity_id||'')});
 const loadRows=()=>activity?api<Roster[]>('adminActivityRoster',{activity_id:activity}).then(setRows):Promise.resolve();
 useEffect(()=>{loadActivities().catch(e=>setMsg(e.message))},[]);useEffect(()=>{if(activity){setSelected(null);setImportRows([]);loadRows().catch(e=>setMsg(e.message))}},[activity]);
 const open=async(r:Roster)=>{setSelected(r);setScore(Number(r.grade?.score||0));setFeedback(r.grade?.feedback_html||'');setComment('');setPublished(r.grade?.published!==false);setRubricScores({});if(rubricFor(activity)){try{const x=await api<EvalResponse>('adminGetRubricEvaluation',{activity_id:activity,user_id:r.user.user_id});setRubricScores(x.evaluation?.scores||{})}catch(e){setMsg(e instanceof Error?e.message:String(e))}}};
 const rubricTotal=useMemo(()=>localRubric?rubricScore100(localRubric,rubricScores):score,[localRubric,rubricScores,score]);
 const rubricComplete=!!localRubric&&localRubric.criteria.every(c=>Number(rubricScores[c.id])>=1&&Number(rubricScores[c.id])<=4);
 const save=async()=>{if(!selected)return;try{if(localRubric){if(!rubricComplete){setMsg('Lengkapi skor 1–4 pada seluruh kriteria rubrik.');return;}await api('adminSaveRubricEvaluation',{activity_id:activity,user_id:selected.user.user_id,submission_id:selected.submission?.submission_id||'',scores:rubricScores,feedback_html:feedback,published});setMsg(`Rubrik tersimpan. Nilai akhir ${rubricTotal}/100.`)}else{if(score<0||score>100){setMsg('Nilai harus 0–100.');return;}await api('adminSaveGrade',{activity_id:activity,user_id:selected.user.user_id,submission_id:selected.submission?.submission_id||'',score,feedback_html:feedback,published});setMsg('Nilai tersimpan.')}await loadRows()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 const sendComment=async()=>{if(!selected?.submission?.submission_id||!strip(comment))return;try{await api('adminAddSubmissionComment',{submission_id:selected.submission.submission_id,content_html:comment});setComment('');setMsg('Komentar dosen terkirim tanpa mengubah nilai.');await loadRows()}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 const evidence=useMemo(()=>rows.filter(r=>current?.type==='discussion'?(Number(r.post_count)||0)>0:!!r.submission),[rows,current?.type]);
 const exportRows=async()=>{if(!current)return;const XLSX=await import('xlsx');const data=evidence.map(r=>({activity_id:activity,user_id:r.user.user_id,submission_id:r.submission?.submission_id||'',NIM:r.user.nim,Nama:r.user.name,Kelas:r.user.class_name||'',Aktivitas:current.title,Bukti:current.type==='discussion'?(r.discussion_excerpt||''):[strip(r.submission?.content_html||''),r.submission?.link_url||'',r.submission?.file_url||''].filter(Boolean).join(' | '),Nilai:r.grade?.score??'',Komentar:''}));const ws=XLSX.utils.json_to_sheet(data);ws['!cols']=[{hidden:true},{hidden:true},{hidden:true},{wch:15},{wch:28},{wch:14},{wch:40},{wch:70},{wch:12},{wch:70}];const guide=XLSX.utils.aoa_to_sheet([['PETUNJUK'],['Isi kolom Komentar. Nilai boleh dikosongkan bila hanya memberi komentar.'],['Jangan mengubah activity_id, user_id, submission_id.'],['Rubrik lima tugas utama dinilai lebih baik langsung dari Gradebook LMS.']]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'PENILAIAN');XLSX.utils.book_append_sheet(wb,guide,'PETUNJUK');XLSX.writeFile(wb,`METOPEN_${activity}_${new Date().toISOString().slice(0,10)}.xlsx`)};
 const readImport=async(file:File|null)=>{if(!file)return;setImportName(file.name);try{const XLSX=await import('xlsx');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),sh=wb.Sheets['PENILAIAN']||wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sh,{defval:'',raw:false});setImportRows(raw.map(r=>{const low:Record<string,unknown>={};Object.keys(r).forEach(k=>low[k.toLowerCase().trim()]=r[k]);return{activity_id:String(low.activity_id||''),user_id:String(low.user_id||''),submission_id:String(low.submission_id||''),score:String(low.nilai??low.score??''),comment:String(low.komentar??low.comment??''),name:String(low.nama??''),nim:String(low.nim??'')}}).filter(x=>x.user_id))}catch(e){setMsg(e instanceof Error?e.message:String(e))}};
 const importErrors=useMemo(()=>importRows.map((r,i)=>{const a=[] as string[];const n=r.score===''?null:Number(r.score);if(r.activity_id!==activity)a.push('activity_id tidak sesuai');if(!r.user_id)a.push('user_id kosong');if(n!==null&&(isNaN(n)||n<0||n>100))a.push('nilai harus kosong/0–100');if(!r.comment)a.push('komentar kosong');return a.length?`Baris ${i+2}: ${a.join(', ')}`:''}).filter(Boolean),[importRows,activity]);
 const runImport=async()=>{if(!importRows.length||importErrors.length)return;setBusy(true);try{let report:ImportReport={processed:0,grade_records:0,comments:0,group_rows:0,errors:[]};for(let i=0;i<importRows.length;i+=50){const x=await api<ImportReport>('adminImportGrades',{rows:importRows.slice(i,i+50).map(r=>({activity_id:r.activity_id,user_id:r.user_id,submission_id:r.submission_id,score:r.score===''?null:Number(r.score),comment:r.comment}))});report={processed:report.processed+x.processed,grade_records:report.grade_records+x.grade_records,comments:report.comments+x.comments,group_rows:report.group_rows+x.group_rows,errors:[...report.errors,...x.errors]}}setMsg(`Import selesai: ${report.processed} baris, ${report.grade_records} nilai, ${report.comments} komentar.`);setImportRows([]);setImportName('');await loadRows()}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <AuthGate adminOnly><AppShell title="Gradebook & Rubrik"><div className="stack">
 <GlassCard><div className="row between wrap gap"><label className="field grow"><span>Pilih aktivitas</span><select value={activity} onChange={e=>setActivity(e.target.value)}>{activities.map(a=><option key={a.activity_id} value={a.activity_id}>{a.week_id} • {a.title}</option>)}</select></label><div className="row wrap gap"><button className="button soft" onClick={exportRows}><Download/>Export Excel</button><label className="button primary"><Upload/>Import Komentar/Nilai<input className="hidden" type="file" accept=".xlsx,.xls" onChange={e=>readImport(e.target.files?.[0]||null)}/></label></div></div><p className="muted">Lima tugas utama otomatis memakai rubrik sumber. Aktivitas lain dapat dinilai manual pada skala 0–100. Excel mendukung komentar dan nilai aktivitas, termasuk diskusi.</p></GlassCard>
 {importRows.length>0&&<GlassCard><div className="row between"><div><span className="eyebrow">PREVIEW IMPORT</span><h3>{importName}</h3></div><span className={importErrors.length?'badge danger':'badge success'}>{importErrors.length?<><AlertTriangle/> {importErrors.length} masalah</>:<><CheckCircle2/> Siap import</>}</span></div>{importErrors.length>0&&<div className="error-box">{importErrors.slice(0,10).map((x,i)=><div key={i}>{x}</div>)}</div>}<div className="right-actions"><button className="button primary" disabled={busy||!!importErrors.length} onClick={runImport}><FileSpreadsheet/>{busy?'Mengimpor...':`Import ${importRows.length} baris`}</button></div></GlassCard>}
 <div className="admin-split"><GlassCard className="admin-list"><span className="eyebrow">MAHASISWA</span><h3>{rows.length} peserta</h3><div className="scroll-list">{rows.map(r=><button key={r.user.user_id} onClick={()=>open(r)} className={selected?.user.user_id===r.user.user_id?'select-row active':'select-row'}><strong>{r.user.name}</strong><small>{r.user.nim} • {r.grade?`${r.grade.score}/100`:'Belum dinilai'}{typeof r.post_count==='number'?` • ${r.post_count} post`:''}</small></button>)}</div></GlassCard><div className="stack">{selected&&<>
 <GlassCard><span className="eyebrow">BUKTI BELAJAR</span><h3>{selected.user.name}</h3>{selected.submission?<><RichHtml html={selected.submission.content_html||''}/><div className="row wrap gap">{selected.submission.link_url&&<a target="_blank" rel="noreferrer" className="button soft compact" href={selected.submission.link_url}><ExternalLink/>Buka URL</a>}{selected.submission.file_url&&<a target="_blank" rel="noreferrer" className="button soft compact" href={selected.submission.file_url}><ExternalLink/>Buka File</a>}</div><label className="field"><span>Komentar dosen tanpa memberi nilai</span><RichTextEditor value={comment} onChange={setComment} minHeight={120}/></label><div className="right-actions"><button className="button soft" disabled={!strip(comment)} onClick={sendComment}><MessageSquareText/>Kirim Komentar</button></div></>:<p className="muted">{typeof selected.post_count==='number'?`Jumlah post diskusi: ${selected.post_count}`:'Belum ada submission.'}</p>}</GlassCard>
 {localRubric?<GlassCard><span className="eyebrow">RUBRIK PENILAIAN</span><h3>{localRubric.name}</h3>{localRubric.sourceWeightTotal!==100&&<div className="notice">Bobot sumber berjumlah {localRubric.sourceWeightTotal}%. Nilai dinormalisasi ke skala 100.</div>}<div className="rubric-table">{localRubric.criteria.map(c=><div className="rubric-score-grid" key={c.id}><div><strong>{c.name}</strong><small>Bobot {c.weight}%</small></div><select value={rubricScores[c.id]||''} onChange={e=>setRubricScores({...rubricScores,[c.id]:Number(e.target.value)})}><option value="">Pilih skor</option>{[4,3,2,1].map(n=><option key={n} value={n}>{n} — {c.levels.find(l=>l.score===n)?.description}</option>)}</select></div>)}</div><div className="rubric-total"><span>Nilai rubrik</span><strong>{rubricComplete?rubricTotal.toFixed(2):'—'} / 100</strong></div><label className="field"><span>Feedback penilaian</span><RichTextEditor value={feedback} onChange={setFeedback} minHeight={180}/></label><label className="switch-row"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Publikasikan ke mahasiswa</label><div className="right-actions"><button className="button primary" onClick={save}><Save/>Simpan Rubrik & Nilai</button></div></GlassCard>:
 <GlassCard><div className="form-grid two"><label className="field"><span>Nilai 0–100</span><input type="number" min="0" max="100" value={score} onChange={e=>setScore(Number(e.target.value))}/></label><label className="switch-row"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Publikasikan</label></div><label className="field"><span>Feedback</span><RichTextEditor value={feedback} onChange={setFeedback} minHeight={180}/></label><div className="right-actions"><button className="button primary" onClick={save}><Save/>Simpan Nilai</button></div></GlassCard>}
 </>}</div></div>{msg&&<div className="notice selectable">{msg}</div>}</div></AppShell></AuthGate>}
