var UPLOAD_CONFIG = {
  ROOT_FOLDER_ID: 'PASTE_ROOT_FOLDER_ID',
  MAX_UPLOAD_BYTES: 5 * 1024 * 1024,
  MAX_CHUNK_BYTES: 2 * 1024 * 1024,
  FILE_SHARING_MODE: 'LINK_VIEWER',
  CHUNK_ROOT_FOLDER: '99_UploadChunks'
};
