import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const config=read('src/lib/courseConfig.ts'),rubrics=read('src/lib/taskRubrics.ts'),setup=read('apps-script/Setup.gs'),manifest=read('public/manifest.webmanifest'),readme=read('README.md'),appShell=read('src/components/AppShell.tsx');
const checks=[];const add=(name,ok)=>checks.push({name,ok});
add('branding METOPEN PFIS',config.includes("APP_NAME='METOPEN PFIS'")&&manifest.includes('METOPEN PFIS')&&appShell.includes('METOPEN PFIS'));
add('3 SKS',config.includes('COURSE_SKS=3'));
add('16 pertemuan',Array.from({length:16},(_,i)=>config.includes(`base(${i+1},`)).every(Boolean));
add('3 CPMK',config.includes('CPMK 1:')&&config.includes('CPMK 2:')&&config.includes('CPMK 3:'));
add('5 tugas formal',['TASK1_ISSUE','TASK2_GAP','TASK3_DESIGN','TASK4_INSTRUMENT','TASK5_PROPOSAL'].every(x=>config.includes(x)&&setup.includes(x)));
add('Tugas 1 minimal 5 artikel',config.includes('minimal 5 artikel')&&setup.includes('minimal <strong>5 artikel'));
add('Proposal BAB I–BAB III',config.includes('BAB I–BAB III')&&setup.includes('BAB I–BAB III'));
add('5 rubrik',['TASK1_ISSUE','TASK2_GAP','TASK3_DESIGN','TASK4_INSTRUMENT','TASK5_PROPOSAL'].every(x=>rubrics.includes(x)));
add('Task 3 total weight 100',rubrics.includes('sourceWeightTotal:100')&&rubrics.includes("name:'Rencana analisis data',weight:25")&&setup.includes("criterion_('T3C5','Rencana analisis data',25"));
add('16 materi seed',setup.includes('var units=[')&&setup.includes("['Evaluasi Akhir Semester dan Finalisasi Proposal'")&&setup.includes("material_id:'MAT'")&&!setup.includes('pairs.forEach'));
add('rubrik backend seeded',setup.includes('function seedRubrics_()')&&setup.includes("rubric_id:'R_TASK5'"));
add('PWA standalone',manifest.includes('standalone'));
add('README course correct',readme.includes('PFS115036')&&readme.includes('3 SKS'));
add('tidak membawa branding MPF',!readme.includes('Multimedia Pembelajaran Fisika'));
const failed=checks.filter(x=>!x.ok);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'} ${c.name}`);if(failed.length)process.exit(1);
