import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const config=read('src/lib/courseConfig.ts');
const rubrics=read('src/lib/taskRubrics.ts');
const schema=read('supabase/schema.sql');
const seed=read('supabase/seed.sql');
const api=read('src/app/api/lms/route.ts');
const task=read('src/app/tasks/[id]/page.tsx');
const projects=read('src/app/projects/page.tsx');
const uploadApi=read('src/app/api/gas/route.ts');
const uploadGs=read('apps-script/Api.gs');
const manifest=read('public/manifest.webmanifest');
const readme=read('README.md');
const appShell=read('src/components/AppShell.tsx');
const checks=[];const add=(name,ok)=>checks.push({name,ok});
const taskIds=['TASK1_ISSUE','TASK2_GAP','TASK3_DESIGN','TASK4_INSTRUMENT','TASK5_PROPOSAL'];
add('branding METOPEN PFIS',config.includes("APP_NAME='METOPEN PFIS'")&&manifest.includes('METOPEN PFIS')&&appShell.includes('METOPEN PFIS'));
add('3 SKS',config.includes('COURSE_SKS=3'));
add('16 pertemuan',Array.from({length:16},(_,i)=>config.includes(`base(${i+1},`)).every(Boolean));
add('3 CPMK',config.includes('CPMK 1:')&&config.includes('CPMK 2:')&&config.includes('CPMK 3:'));
add('5 tugas formal',taskIds.every(x=>config.includes(x)&&api.includes(x)));
add('Tugas 1 lima artikel',config.includes('minimal 5 artikel')&&task.includes('SUMBER ARTIKEL • WAJIB 5')&&schema.includes('submission_articles'));
add('Proposal BAB I–BAB III',config.includes('BAB I–BAB III')&&task.includes('proposal BAB I–BAB III'));
add('5 rubrik',taskIds.every(x=>rubrics.includes(x)));
add('Task 3 total weight 100',rubrics.includes('sourceWeightTotal:100')&&rubrics.includes("name:'Rencana analisis data',weight:25"));
add('database Supabase',schema.includes('create table if not exists public.users')&&schema.includes('enable row level security')&&api.includes("backend:'supabase'"));
add('seed Supabase lengkap',seed.includes("'W16'")&&seed.includes("'MAT016'")&&seed.includes("'TASK5_PROPOSAL'")&&seed.includes("'R_TASK5'"));
add('karya mahasiswa tersedia',projects.includes('Karya Mahasiswa')&&api.includes('listPublicProjects')&&api.includes('getPublicProject'));
add('Apps Script upload-only',uploadApi.includes('UPLOAD_ACTIONS')&&uploadGs.includes("action==='uploadAsset'")&&uploadGs.includes("action==='uploadChunk'")&&!uploadGs.includes('login'));
add('PWA standalone',manifest.includes('standalone'));
add('README course correct',readme.includes('PFS115036')&&readme.includes('3 SKS')&&readme.includes('Supabase'));
add('tidak membawa branding MPF',!readme.includes('Multimedia Pembelajaran Fisika'));
const failed=checks.filter(x=>!x.ok);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'} ${c.name}`);if(failed.length)process.exit(1);
