'use client';
import { useState } from 'react';
import Link from 'next/link';
import AppShell from '@/components/AppShell';
import AuthGate from '@/components/AuthGate';
import GlassCard from '@/components/GlassCard';
import { COURSE_NAME,COURSE_CODE,COURSE_SEMESTER,COURSE_SKS,COURSE_CONTACT_MINUTES,COURSE_TAGLINE,MEETINGS,PHASES,RPS_ASSESSMENT_WEIGHTS,CPMK,CPL,FORMAL_TASKS } from '@/lib/courseConfig';
import { ScrollText,CalendarDays,Clock3,Target,CheckCircle2,ArrowRight,ChevronDown,ChevronUp,Flag,Route,Download,ClipboardCheck } from 'lucide-react';
export default function RencanaPembelajaranPage(){const[expanded,setExpanded]=useState<number|null>(1);return <AuthGate><AppShell title="Rencana Pembelajaran Semester"><div className="stack rpp-page">
<section className="rpp-hero glass-panel"><div className="rpp-hero-copy"><span className="rpp-icon"><ScrollText/></span><div><span className="eyebrow">RPS OBE • {COURSE_CODE} • SEMESTER {COURSE_SEMESTER}</span><h2>{COURSE_NAME}</h2><p>{COURSE_TAGLINE}. LMS mengikuti RPS sebagai struktur pertemuan dan kisi-kisi tugas sebagai sumber lima produk tugas beserta rubriknya.</p><div className="row wrap gap"><a className="button soft compact" href="/rps/METOPEN-PFIS-OBE-IKA.docx" download><Download/>Unduh RPS</a><a className="button soft compact" href="/tugas/Kisi-kisi-Tugas-METOPEN-PFIS-2026.pdf" download><Download/>Unduh Kisi-kisi Tugas & Rubrik</a></div></div></div><div className="rpp-hero-stats"><div><CalendarDays/><strong>16</strong><span>Pertemuan</span></div><div><Clock3/><strong>{COURSE_SKS}</strong><span>SKS • RPS menulis {COURSE_CONTACT_MINUTES} menit/pertemuan</span></div><div><ClipboardCheck/><strong>{FORMAL_TASKS.length}</strong><span>Tugas Produk</span></div></div></section>
<GlassCard><span className="eyebrow">CAPAIAN PEMBELAJARAN PRODI</span>{CPL.map((x,i)=><p key={i}><CheckCircle2 size={16}/> {x}</p>)}</GlassCard>
<GlassCard><span className="eyebrow">CAPAIAN PEMBELAJARAN MATA KULIAH</span><div className="stack small-gap">{CPMK.map((x,i)=><p key={i}><CheckCircle2 size={16}/> {x}</p>)}</div></GlassCard>
<div className="rpp-summary-grid">{PHASES.map(p=><GlassCard className="rpp-summary-card" key={p.no}><div className="icon-bubble teal"><Flag/></div><div><span className="eyebrow">FASE {p.no}</span><strong>{p.label}</strong><small>{p.range}</small></div></GlassCard>)}</div>
<GlassCard><span className="eyebrow">BOBOT YANG TERTULIS PADA TABEL RPS</span><div className="row wrap gap">{RPS_ASSESSMENT_WEIGHTS.map(a=><span className="badge" key={a.code}>{a.label} • {a.weight}%</span>)}</div><p className="source-note">UTS dan UAS disebutkan sebagai Evaluasi Tengah/Akhir Semester pada RPS, tetapi tabel sumber tidak memberi bobot terpisah. LMS tidak menambahkan bobot UTS/UAS yang tidak tersedia pada sumber; dosen dapat mengatur aktivitas dan nilai sesuai kebijakan kelas.</p></GlassCard>
<GlassCard><span className="eyebrow">LIMA PRODUK TUGAS</span><div className="stack small-gap">{FORMAL_TASKS.map(t=><Link key={t.code} href={`/tasks/${t.code}`} className="list-card"><div className="icon-bubble amber"><ClipboardCheck/></div><div className="grow"><strong>Tugas {t.no} — {t.title}</strong><small>{t.cpmk} • Pertemuan acuan {t.week}</small><p className="muted tiny">{t.short}</p></div><ArrowRight/></Link>)}</div></GlassCard>
<div className="section-title"><div><span className="eyebrow">TIMELINE SEMESTER</span><h2>16 Pertemuan dalam Tiga Fase</h2></div><span className="badge success"><Route/>OBE Research Journey</span></div><div className="rpp-timeline">{MEETINGS.map(m=>{const open=expanded===m.no;return <article className={`rpp-meeting glass-card ${open?'open':''}`} key={m.no}><span className="rpp-timeline-dot">{String(m.no).padStart(2,'0')}</span><div className="rpp-meeting-head"><div className="grow"><div className="row wrap gap"><span className="eyebrow">PERTEMUAN {m.no} • FASE {m.phase}</span><span className="badge">{m.mode}</span></div><h3>{m.title}</h3></div><button className="button soft compact" onClick={()=>setExpanded(open?null:m.no)}>{open?<ChevronUp/>:<ChevronDown/>}{open?'Ringkas':'Detail'}</button></div>{m.activityHref&&<div className="rpp-checkpoints"><Link href={m.activityHref} className="checkpoint-chip checkpoint-project"><CheckCircle2/>{m.activityLabel}</Link></div>}{open&&<div className="rpp-detail"><div className="rpp-objectives"><div className="rpp-detail-title"><Target/><div><span className="eyebrow">CAPAIAN</span><h4>{m.cpmk.join(' • ')}</h4></div></div><ul>{m.objectives.map((x,i)=><li key={i}><CheckCircle2/>{x}</li>)}</ul></div><div className="rpp-phases"><div className="rpp-phase before"><span className="eyebrow">SEBELUM</span><ul>{m.before.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div className="rpp-phase during"><span className="eyebrow">SAAT KELAS</span><ul>{m.during.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div className="rpp-phase after"><span className="eyebrow">SETELAH</span><ul>{m.after.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div><div className="rpp-output-box"><div className="grow"><span className="eyebrow">BUKTI PROSES</span>{m.outputs.map((x,i)=><p key={i}>{x}</p>)}</div><Link href={`/weeks/${m.no}`} className="button primary compact">Buka Pertemuan <ArrowRight/></Link></div></div>}</article>})}</div>
</div></AppShell></AuthGate>}
